-- V2__init_region_schema.sql

CREATE TABLE IF NOT EXISTS regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sido_code VARCHAR(20) NOT NULL,
    sido_name VARCHAR(100) NOT NULL,
    sigungu_code VARCHAR(20) NOT NULL,
    sigungu_name VARCHAR(100) NOT NULL,
    kma_nx INT,
    kma_ny INT,
    asos_station_id VARCHAR(20),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_regions_sido_sigungu UNIQUE (sido_code, sigungu_code)
);

CREATE TABLE IF NOT EXISTS region_analyses (
    id VARCHAR(36) PRIMARY KEY,
    idempotency_key VARCHAR(100),
    user_email VARCHAR(255) NOT NULL,
    sido_code VARCHAR(20) NOT NULL,
    sido_name VARCHAR(100) NOT NULL,
    sigungu_code VARCHAR(20) NOT NULL,
    sigungu_name VARCHAR(100) NOT NULL,
    region_score INT,
    grade VARCHAR(50),
    summary TEXT,
    confidence_grade VARCHAR(50),
    confidence_score INT,
    confidence_message TEXT,
    payload_json TEXT,
    analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    data_mode VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_analyses_user_sigungu_analyzed ON region_analyses(user_email, sigungu_code, analyzed_at DESC);

-- Seed Region Catalog Data (including Jeonbuk Gochang-gun as main spec target)
INSERT INTO regions (sido_code, sido_name, sigungu_code, sigungu_name, kma_nx, kma_ny, asos_station_id, enabled)
VALUES
  ('52', '전북특별자치도', '52180', '고창군', 52, 77, '172', true),
  ('52', '전북특별자치도', '52110', '전주시', 63, 89, '146', true),
  ('52', '전북특별자치도', '52140', '익산시', 60, 91, '146', true),
  ('41', '경기도', '41110', '수원시', 60, 121, '119', true),
  ('41', '경기도', '41460', '용인시', 64, 121, '119', true),
  ('41', '경기도', '41500', '이천시', 68, 121, '203', true),
  ('42', '강원특별자치도', '42150', '강릉시', 92, 131, '105', true),
  ('42', '강원특별자치도', '42110', '춘천시', 73, 134, '101', true),
  ('43', '충청북도', '43110', '청주시', 69, 107, '131', true),
  ('43', '충청북도', '43130', '충주시', 76, 114, '127', true),
  ('44', '충청남도', '44200', '논산시', 62, 99, '133', true),
  ('44', '충청남도', '44150', '공주시', 63, 102, '133', true),
  ('46', '전라남도', '46170', '나주시', 56, 71, '156', true),
  ('46', '전라남도', '46810', '해남군', 54, 61, '261', true),
  ('47', '경상북도', '47250', '상주시', 81, 107, '137', true),
  ('47', '경상북도', '47110', '포항시', 102, 94, '138', true),
  ('48', '경상남도', '48120', '창원시', 90, 77, '155', true),
  ('48', '경상남도', '48170', '진주시', 86, 75, '192', true),
  ('50', '제주특별자치도', '50110', '제주시', 52, 38, '184', true),
  ('50', '제주특별자치도', '50130', '서귀포시', 52, 33, '189', true)
ON CONFLICT (sido_code, sigungu_code) DO NOTHING;
