CREATE TABLE IF NOT EXISTS user_inquiries (
    id BIGSERIAL PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    inquiry_text TEXT NOT NULL,
    category VARCHAR(50) DEFAULT 'GENERAL',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_inquiries_email ON user_inquiries(user_email);
